// app/server/src/jobs/retention.ts
// Nightly retention sweep. PLAN §8.

import { readdir, stat, unlink } from 'node:fs/promises';
import { join } from 'node:path';

import { getConfig } from '../config.js';
import * as db from '../db.js';
import { deleteFileBestEffort } from '../fs-utils.js';
import { childLogger } from '../logger.js';

const logger = childLogger('retention-job');

/** Default clip retention window — 14 days. Overridden by `clip_retention_days` setting. */
const CLIP_RETENTION_DAYS_DEFAULT = 14;

export interface RetentionRunResult {
  snapshots_deleted: number;
  timelapse_media_cleared: number;
  audit_rows_deleted: number;
  clips_deleted: number;
  thumbnails_deleted: number;
}

function days(n: number): number {
  return n * 24 * 60 * 60 * 1000;
}

function readSettingInt(key: string, fallback: number): number {
  const raw = db.getSetting(key);
  if (!raw) return fallback;
  const parsed = Number.parseInt(raw, 10);
  return Number.isFinite(parsed) ? parsed : fallback;
}

export async function runRetentionJob(): Promise<RetentionRunResult> {
  const now = Date.now();
  const snapWindow = days(readSettingInt('snapshot_retention_days', 90));
  const tlWindow = days(readSettingInt('timelapse_retention_days', 30));
  const auditWindow = days(readSettingInt('audit_retention_days', 365));
  const clipWindow = days(readSettingInt('clip_retention_days', CLIP_RETENTION_DAYS_DEFAULT));

  // Snapshots — delete file then row.
  const snapshotsToDelete = db.listSnapshotsBetween(0, now - snapWindow);
  for (const snap of snapshotsToDelete) {
    await deleteFileBestEffort(snap.path);
  }
  const snapshotsDeleted = db.deleteSnapshotsOlderThan(now - snapWindow);
  const snapshotDiaryDeleted = db.deleteOldSnapshotDiaryEntries(now - snapWindow);

  // Timelapses — clear the media file + null out the media_path column.
  // The diary entry itself stays so the audit/admin history isn't rewritten.
  const cutoffTl = now - tlWindow;
  const oldTimelapses = db.listDiaryEntriesByKindBetween('timelapse', 0, cutoffTl);
  let timelapseFiles = 0;
  for (const entry of oldTimelapses) {
    if (entry.media_path) {
      await deleteFileBestEffort(entry.media_path);
      timelapseFiles += 1;
    }
  }
  db.clearOldTimelapseMedia(cutoffTl);

  const auditRowsDeleted = db.deleteAuditOlderThan(now - auditWindow);

  // Clips — extracted MP4s cached by clips.ts / Send-a-Clip.
  const clipsDeleted = await pruneMediaDir('clips', now - clipWindow);

  // Thumbnails — downscaled JPEGs generated by thumbnails.ts.
  // Prune on the same window as clips; stale thumbnails re-generate lazily.
  const thumbnailsDeleted = await pruneMediaDir('thumbnails', now - clipWindow);

  // Also opportunistically purge expired sessions — cheap and keeps the
  // table from growing forever in a long-lived install.
  db.purgeExpiredSessions(now);

  logger.info(
    {
      snapshotsDeleted,
      snapshotDiaryDeleted,
      timelapseFiles,
      auditRowsDeleted,
      clipsDeleted,
      thumbnailsDeleted,
    },
    'retention sweep complete',
  );
  return {
    snapshots_deleted: snapshotsDeleted,
    timelapse_media_cleared: timelapseFiles,
    audit_rows_deleted: auditRowsDeleted,
    clips_deleted: clipsDeleted,
    thumbnails_deleted: thumbnailsDeleted,
  };
}

/**
 * Delete files under `STORAGE_PATH/<subdir>/` that are older than `cutoffMs`.
 * Best-effort per file — one failure does not abort the rest.
 */
async function pruneMediaDir(subdir: string, cutoffMs: number): Promise<number> {
  const cfg = getConfig();
  const dir = join(cfg.STORAGE_PATH, subdir);
  let deleted = 0;
  let entries: string[];
  try {
    entries = await readdir(dir);
  } catch (err: unknown) {
    // Directory doesn't exist yet — nothing to prune.
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return 0;
    logger.warn({ subdir, err: (err as Error).message }, 'media dir readdir failed');
    return 0;
  }
  for (const name of entries) {
    const abs = join(dir, name);
    try {
      const info = await stat(abs);
      if (info.mtimeMs < cutoffMs) {
        await unlink(abs);
        deleted += 1;
      }
    } catch (err: unknown) {
      if ((err as NodeJS.ErrnoException).code !== 'ENOENT') {
        logger.warn({ path: abs, err: (err as Error).message }, 'failed to prune media file');
      }
    }
  }
  return deleted;
}
